/*
tuya_app_config.h
Copyright(C),2018-2020, 涂鸦科技 www.tuya.comm
*/

/* AUTO-GENERATED FILE. DO NOT MODIFY !!!
*
* This config file is automatically generated by tuya cross-build system.
* It should not be modified by hand.
*/

#ifndef TUYA_APP_CONFIG_H
#define TUYA_APP_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#define TUYA_MODULE_T5 1
#define ENABLE_AI_MODE_HOLD 1
#define ENABLE_AI_MODE_ONESHOT 1
#define ENABLE_AI_MODE_WAKEUP 1
#define ENABLE_AI_MODE_FREE 1
#define ENABLE_AI_MODE_PICTURE 1
#define ENABLE_DEFAULT_SESSION 1
#define T5AI_BOARD 1
// CONFIG_T5AI_BOARD_EYES is not set
// CONFIG_T5AI_BOARD_EVB is not set
// CONFIG_T5AI_BOARD_EVB_PRO is not set
// CONFIG_T5AI_BOARD_ROBOT is not set
// CONFIG_T5AI_BOARD_DESKTOP is not set
// CONFIG_T2AI_BOARD is not set
// CONFIG_LE270AI_BOARD is not set
// CONFIG_WUKONG_BOARD_UBUNTU is not set
#define ENABLE_T5AI_BOARD_UI_DESKTOP 1

//
// Pin Configuration
//
#define TUYA_AI_TOY_AUDIO_TRIGGER_PIN_NUM 12
#define TUYA_AI_TOY_SPK_EN_PIN_NUM 28
#define TUYA_AI_TOY_LED_PIN_NUM 56
#define TUYA_AI_TOY_NET_PIN_NUM 64
// CONFIG_DEVICE_POWER_CONTROL is not set
// end of Pin Configuration

//
// Display Configuration
//
#define TUYA_LCD_IC_NAME_STR "ili9488"
#define TUYA_LCD_WIDTH_VAL 320
#define TUYA_LCD_HEIGHT_VAL 480
#define LCD_FPS_VAL 10
#define TUYA_LCD_ROTATION_VAL 0
// end of Display Configuration

//
// AI Agent Scode Configuration
//
#define AI_AGENT_SCODE_CHAT ""
#define AI_AGENT_SCODE_TRANSLATE "asr-llm-tts"
#define AI_AGENT_SCODE_PICTURE ""
#define AI_AGENT_SCODE_DETECTION ""
// end of AI Agent Scode Configuration

// CONFIG_ENABLE_BATTERY is not set
#define ENABLE_TUYA_CAMERA 1
#define ENABLE_AI_MODE_P2P 1

//
// Camera Hardware Configuration
//
#define CAMERA_TYPE_DVP 1
// CONFIG_CAMERA_TYPE_UVC is not set
#define TUYA_AI_TOY_ISP_WIDTH_VAL 480
#define TUYA_AI_TOY_ISP_HEIGHT_VAL 480
#define TUYA_AI_TOY_ISP_FPS_VAL 10
#define TUYA_AI_TOY_POWER_PIN_NUM 51
#define TUYA_AI_TOY_I2C_CLK_PIN_NUM 13
#define TUYA_AI_TOY_I2C_SDA_PIN_NUM 15
// end of Camera Hardware Configuration

#define ENABLE_TUYA_PICTURE 1
#define TUYA_PICTURE_ALBUM_NAME "ai_picture"
#define TUYA_PICTURE_ALBUM_MAX_IMAGE_CNT 10
#define TUYA_PICTURE_DEF_OUTPUT_WIDTH 320
#define TUYA_PICTURE_DEF_OUTPUT_HEIGHT 480
#define ENABLE_TAL_IMAGE 1
#define ENABLE_IMAGE_ALBUM 1
#define ENABLE_IMAGE_ALBUM_STORAGE_MEM 1
// CONFIG_ENABLE_IMAGE_ALBUM_STORAGE_SD is not set
#define ENABLE_TUYA_TOOLKITS 1
// CONFIG_ENABLE_TOOLKITS_CAMERA is not set
// CONFIG_ENABLE_TOOLKITS_TM is not set
#define ENABLE_TOOLKITS_CONTROL 1
// CONFIG_ENABLE_TOOLKITS_PLAYBACK is not set
// CONFIG_ENABLE_TOOLKITS_IMM is not set
// CONFIG_ENABLE_TOOLKITS_SOCIAL is not set
#define ENABLE_TUYA_UI 1
#define TUYA_CPU_ARCH_SMP 1
#define TUYA_MULTI_TYPES_LCD 1
#define TUYA_APP_DRIVERS_TP 1
#define RGB565_COLOR_SWAP_LVGL 1
#define RGB888_COLOR_SWAP_LVGL 1
#define TUYA_LVGL_VERSION 8
// CONFIG_TUYA_IMG_DIRECT_FLUSH is not set
#define TUYA_LVGL_DRAW_WITH_ARM2D 1
#define TUYA_DMA2D_SHARE 1
#define TUYA_FILE_SYSTEM 1
#define FILE_SYSTEM_LFS_SD 1
// CONFIG_FILE_SYSTEM_LFS_SPI_FLASH is not set
#define TUYA_LIBJPEG_TURBO 1
#define TUYA_LIB_FREETYPE 1
#define TUYA_AI_TOY_DEMO 1

//
// Audio Configuration
//

//
// Audio Input
//

//
// --- Source ---
//
// CONFIG_USING_UART_AUDIO_INPUT is not set
#define USING_BOARD_AUDIO_INPUT 1
#define INPUT_BOARD_STACK_SIZE 2560

//
// --- Frontend ---
//
#define USING_TUYA_AUDIO_FRONTEND 1
// CONFIG_USING_3RD_AUDIO_FRONTEND is not set

//
// --- Encoder ---
//
#define ENABLE_APP_OPUS_ENCODER 1
// CONFIG_ENABLE_APP_SPEEX_ENCODER is not set
#define APP_OPUS_ENCODER_BITRATE 16000
#define APP_OPUS_ENCODER_BANDWIDTH 1102
// end of Audio Input

//
// Audio Output
//

//
// --- Target ---
//
// CONFIG_USING_UART_AUDIO_OUTPUT is not set
#define USING_BOARD_AUDIO_OUTPUT 1

//
// --- Decoder / Player ---
//
// CONFIG_AI_PLAYER_LITE is not set
#define AI_PLAYER_DECODER_OPUS_ENABLE 1
#define AI_PLAYER_DECODER_OPUS_FRAME_SIZE 40
#define AI_PLAYER_DECODER_OPUS_KBPS 16
#define AI_PLAYER_DECODER_OGGOPUS_ENABLE 1
// end of Audio Output

// CONFIG_CODEC_BENCH_TEST is not set
// end of Audio Configuration

// CONFIG_ENABLE_CELLULAR_DONGLE is not set
// CONFIG_AI_CHAT_DEFAULT_HOLD is not set
#define AI_CHAT_DEFAULT_ONESHOT 1
// CONFIG_AI_CHAT_DEFAULT_WAKEUP is not set
// CONFIG_AI_CHAT_DEFAULT_FREE is not set
// CONFIG_AI_CHAT_DEFAULT_PICTURE is not set
// CONFIG_AI_CHAT_DEFAULT_P2P is not set
#define TUYA_AI_CHAT_DEFAULT_MODE 1

//
// Device Defaults
//
#define TY_SPK_DEFAULT_VOL 70
#define TY_AI_DEFAULT_LANG 1
// CONFIG_ENABLE_AUDIO_ANALYSIS is not set
// CONFIG_ENABLE_APP_AI_MONITOR is not set
// CONFIG_ENABLE_CLOUD_ALERT is not set
// CONFIG_ENABLE_APP_JOYINSIDE is not set
// CONFIG_ENABLE_LOW_POWER is not set
// end of Device Defaults

#ifdef __cplusplus
}
#endif

#endif
