#ifndef __WUKONG_AI_AGENT_H__
#define __WUKONG_AI_AGENT_H__

#include "tuya_cloud_types.h"

typedef enum {
    WUKONG_AI_EVENT_IDLE = -1,
    WUKONG_AI_EVENT_ASR_EMPTY = 0,
    WUKONG_AI_EVENT_ASR_OK,
    WUKONG_AI_EVENT_ASR_ERROR,
    WUKONG_AI_EVENT_TTS_PRE,
    WUKONG_AI_EVENT_TTS_START,
    WUKONG_AI_EVENT_TTS_DATA,
    WUKONG_AI_EVENT_TTS_STOP,
    WUKONG_AI_EVENT_TTS_ABORT,
    WUKONG_AI_EVENT_TTS_ERROR,
    WUKONG_AI_EVENT_VAD_TIMEOUT,
    WUKONG_AI_EVENT_TEXT_STREAM_START,
    WUKONG_AI_EVENT_TEXT_STREAM_DATA,
    WUKONG_AI_EVENT_TEXT_STREAM_STOP,
    WUKONG_AI_EVENT_TEXT_STREAM_ABORT,
    WUKONG_AI_EVENT_EMOTION,
    WUKONG_AI_EVENT_LLM_EMOTION,
    WUKONG_AI_EVENT_SKILL,
    WUKONG_AI_EVENT_CHAT_BREAK,
    WUKONG_AI_EVENT_SERVER_VAD,
    WUKONG_AI_EVENT_END,
    WUKONG_AI_EVENT_PLAY_CTL_PLAY,
    WUKONG_AI_EVENT_PLAY_CTL_RESUME,
    WUKONG_AI_EVENT_PLAY_CTL_PAUSE,
    WUKONG_AI_EVENT_PLAY_CTL_REPLAY,
    WUKONG_AI_EVENT_PLAY_CTL_PREV,
    WUKONG_AI_EVENT_PLAY_CTL_NEXT,
    WUKONG_AI_EVENT_PLAY_CTL_SEQUENTIAL,
    WUKONG_AI_EVENT_PLAY_CTL_SEQUENTIAL_LOOP,
    WUKONG_AI_EVENT_PLAY_CTL_SINGLE_LOOP,
    WUKONG_AI_EVENT_PLAY_CTL_END,
    WUKONG_AI_EVENT_PLAY_END,
    WUKONG_AI_EVENT_PLAY_ALERT,
    WUKONG_AI_EVENT_CLOCK_MCP_COUNTDOWN_TIMER,
    WUKONG_AI_EVENT_CLOCK_MCP_STOPWATCH_TIMER,
    WUKONG_AI_EVENT_CLOCK_MCP_POMODORO_TIMER,
    WUKONG_AI_EVENT_CLOCK_MCP_SCHEDULE,
    WUKONG_AI_EVENT_CLOCK_MCP_ALARM,
    WUKONG_AI_EVENT_ACCEPT_PICTURE,
    WUKONG_AI_EVENT_SEND_PICTURE_END,
    WUKONG_AI_EVENT_EXIT,
} WUKONG_AI_EVENT_TYPE_E;

typedef struct {
    WUKONG_AI_EVENT_TYPE_E type;
    VOID *data;
} WUKONG_AI_EVENT_T;

typedef struct {
    CHAR_T *data;
    UINT_T datalen;
} WUKONG_AI_TEXT_T;

typedef struct {
    CHAR_T *name;
} WUKONG_AI_EMO_T;

#endif
