import type { Hospital } from '../../../entities/hospital.entity.js';

/**
 * 误删恢复用：浙江省公立/大学附属口腔专科及各地「市口腔医院」等。
 * 名称尽量与高德/官网一致，便于 resolveHospitalPoi 匹配。
 */
export function buildPublicStomatologyRestoreSeed(
  seedRow: (p: Partial<Hospital>) => Partial<Hospital>,
): Partial<Hospital>[] {
  return [
    /* ─── 杭州：浙大附属口腔医院各院区（原浙江省口腔医院体系）─── */
    seedRow({
      name: '浙江大学医学院附属口腔医院华家池总院(口腔医学中心)',
      shortName: '浙大口腔华家池',
      province: '浙江省',
      city: '杭州市',
      district: '上城区',
      address: '上城区凯旋路268号附近（华家池，请以官网为准）',
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      sortWeight: 92,
      remark: '公立口腔专科，数据由运营恢复录入',
    }),
    seedRow({
      name: '浙江大学医学院附属口腔医院湖滨(延安)院区',
      shortName: '浙大口腔湖滨',
      province: '浙江省',
      city: '杭州市',
      district: '拱墅区',
      address: '延安路附近院区（请以官网为准）',
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      sortWeight: 91,
    }),
    seedRow({
      name: '浙江大学医学院附属口腔医院紫金港(城西)院区',
      shortName: '浙大口腔紫金港',
      province: '浙江省',
      city: '杭州市',
      district: '拱墅区',
      address: '紫金港/城西院区（请以官网为准）',
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      sortWeight: 91,
    }),
    seedRow({
      name: '浙江大学医学院附属口腔医院大运河(上塘)院区',
      shortName: '浙大口腔大运河',
      province: '浙江省',
      city: '杭州市',
      district: '拱墅区',
      address: '上塘/大运河院区（请以官网为准）',
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      sortWeight: 90,
    }),
    seedRow({
      name: '浙江大学医学院附属口腔医院未来科技城院区',
      shortName: '浙大口腔未来科技城',
      province: '浙江省',
      city: '杭州市',
      district: '余杭区',
      address: '余杭区未来科技城（请以官网为准）',
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      sortWeight: 90,
    }),

    /* ─── 杭州：杭州市口腔医院（市属口腔专科）─── */
    seedRow({
      name: '杭州口腔医院(平海总院)',
      shortName: '杭州市口腔平海',
      province: '浙江省',
      city: '杭州市',
      district: '上城区',
      address: '上城区平海路57号附近（请以官网为准）',
      hospitalLevel: '三级',
      ownershipType: '政府办',
      sortWeight: 89,
    }),
    seedRow({
      name: '杭州口腔医院城西院区',
      shortName: '杭州口腔城西',
      province: '浙江省',
      city: '杭州市',
      district: '西湖区',
      address: '西湖区城西院区（请以官网为准）',
      hospitalLevel: '三级',
      ownershipType: '政府办',
      sortWeight: 88,
    }),
    seedRow({
      name: '杭州口腔医院(湖滨院区)',
      shortName: '杭州口腔湖滨',
      province: '浙江省',
      city: '杭州市',
      district: '上城区',
      address: '湖滨院区（请以官网为准）',
      hospitalLevel: '三级',
      ownershipType: '政府办',
      sortWeight: 88,
    }),
    seedRow({
      name: '杭州口腔医院(紫金港总院)',
      shortName: '杭州口腔紫金港',
      province: '浙江省',
      city: '杭州市',
      district: '西湖区',
      address: '紫金港院区（请以官网为准）',
      hospitalLevel: '三级',
      ownershipType: '政府办',
      sortWeight: 87,
    }),
    seedRow({
      name: '杭州口腔医院萧山分院',
      shortName: '杭州口腔萧山',
      province: '浙江省',
      city: '杭州市',
      district: '萧山区',
      address: '萧山区（请以官网为准）',
      hospitalLevel: '三级',
      ownershipType: '政府办',
      sortWeight: 86,
    }),
    seedRow({
      name: '杭州口腔医院未来科技城院区',
      shortName: '杭州口腔未来科技城',
      province: '浙江省',
      city: '杭州市',
      district: '余杭区',
      address: '余杭区未来科技城（请以官网为准）',
      hospitalLevel: '三级',
      ownershipType: '政府办',
      sortWeight: 86,
    }),
    seedRow({
      name: '杭州余杭口腔医院',
      shortName: '杭州余杭口腔',
      province: '浙江省',
      city: '杭州市',
      district: '余杭区',
      address: '余杭区（请以官网为准）',
      hospitalLevel: '三级',
      ownershipType: '政府办',
      sortWeight: 85,
    }),

    /* ─── 杭州：区县公立口腔专科/院办牙科医院（之前误删中曾含）─── */
    seedRow({
      name: '杭州萧山牙科医院(总院)',
      shortName: '萧山牙科医院',
      province: '浙江省',
      city: '杭州市',
      district: '萧山区',
      address: '萧山区（请以官网为准）',
      hospitalLevel: '二级',
      ownershipType: '政府办',
      sortWeight: 72,
    }),

    /* ─── 温州医科大学体系 ─── */
    seedRow({
      name: '温州医科大学附属口腔医院',
      shortName: '温医大口腔',
      province: '浙江省',
      city: '温州市',
      district: '鹿城区',
      address: '鹿城区学院西路（请以官网为准）',
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      sortWeight: 93,
    }),

    /* ─── 各地级市公立口腔医院（独立法人常见命名）─── */
    seedRow({
      name: '宁波市口腔医院',
      shortName: '宁波口腔',
      province: '浙江省',
      city: '宁波市',
      district: null,
      address: '宁波市（请以官网为准）',
      hospitalLevel: '三级',
      ownershipType: '政府办',
      sortWeight: 82,
    }),
    seedRow({
      name: '嘉兴市口腔医院',
      shortName: '嘉兴口腔',
      province: '浙江省',
      city: '嘉兴市',
      district: null,
      address: '嘉兴市（请以官网为准）',
      hospitalLevel: '二级',
      ownershipType: '政府办',
      sortWeight: 78,
    }),
    seedRow({
      name: '湖州市口腔医院',
      shortName: '湖州口腔',
      province: '浙江省',
      city: '湖州市',
      district: null,
      address: '湖州市（请以官网为准）',
      hospitalLevel: '二级',
      ownershipType: '政府办',
      sortWeight: 78,
    }),
    seedRow({
      name: '绍兴市口腔医院',
      shortName: '绍兴口腔',
      province: '浙江省',
      city: '绍兴市',
      district: null,
      address: '绍兴市（请以官网为准）',
      hospitalLevel: '二级',
      ownershipType: '政府办',
      sortWeight: 78,
    }),
    seedRow({
      name: '金华市口腔医院',
      shortName: '金华口腔',
      province: '浙江省',
      city: '金华市',
      district: null,
      address: '金华市（请以官网为准）',
      hospitalLevel: '二级',
      ownershipType: '政府办',
      sortWeight: 78,
    }),
    seedRow({
      name: '衢州市口腔医院',
      shortName: '衢州口腔',
      province: '浙江省',
      city: '衢州市',
      district: null,
      address: '衢州市（请以官网为准）',
      hospitalLevel: '二级',
      ownershipType: '政府办',
      sortWeight: 78,
    }),
    seedRow({
      name: '舟山市口腔医院',
      shortName: '舟山口腔',
      province: '浙江省',
      city: '舟山市',
      district: null,
      address: '舟山市（请以官网为准）',
      hospitalLevel: '二级',
      ownershipType: '政府办',
      sortWeight: 76,
    }),
    seedRow({
      name: '台州市口腔医院',
      shortName: '台州口腔',
      province: '浙江省',
      city: '台州市',
      district: null,
      address: '台州市（请以官网为准）',
      hospitalLevel: '二级',
      ownershipType: '政府办',
      sortWeight: 78,
    }),
    seedRow({
      name: '丽水市口腔医院',
      shortName: '丽水口腔',
      province: '浙江省',
      city: '丽水市',
      district: null,
      address: '丽水市（请以官网为准）',
      hospitalLevel: '二级',
      ownershipType: '政府办',
      sortWeight: 76,
    }),

    /* ─── 上海：公立口腔防治/专科 ─── */
    seedRow({
      name: '上海市口腔病防治院',
      shortName: '上海口防院',
      province: '上海市',
      city: '上海市',
      district: '黄浦区',
      address: '黄浦区北京东路356号（复兴中路分院等请以官网为准）',
      hospitalLevel: '三级',
      ownershipType: '政府办',
      sortWeight: 90,
    }),
    seedRow({
      name: '复旦大学附属口腔医院',
      shortName: '复旦口腔',
      province: '上海市',
      city: '上海市',
      district: '闵行区',
      address: '闵行区（请以官网为准）',
      hospitalLevel: '三级',
      ownershipType: '政府办',
      sortWeight: 89,
    }),
  ];
}
