import type { Hospital } from '../../../entities/hospital.entity.js';

/** 杭州全市县（区）+ 上海市代表三甲/区域中心骨架；电话与图请高德补全或人工核对 */
export function buildHangzhouShanghaiSeed(
  seedRow: (p: Partial<Hospital>) => Partial<Hospital>,
): Partial<Hospital>[] {
  return [
    /* ─── 杭州市 ─── */
    seedRow({
      name: '浙江大学医学院附属第一医院（庆春院区）',
      shortName: '浙大一院',
      province: '浙江省',
      city: '杭州市',
      district: '上城区',
      address: '上城区庆春路79号（多院区请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['综合诊疗', '多学科协作'],
      sortWeight: 98,
    }),
    seedRow({
      name: '浙江大学医学院附属第二医院（解放路院区）',
      shortName: '浙大二院',
      province: '浙江省',
      city: '杭州市',
      district: '上城区',
      address: '上城区解放路88号附近（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['心血管', '神经外科', '骨科'],
      sortWeight: 97,
    }),
    seedRow({
      name: '浙江大学医学院附属邵逸夫医院（庆春院区）',
      shortName: '邵逸夫医院',
      province: '浙江省',
      city: '杭州市',
      district: '上城区',
      address: '上城区庆春东路3号（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['微创', '肿瘤', '康复'],
      sortWeight: 96,
    }),
    seedRow({
      name: '浙江省人民医院（朝晖院区）',
      shortName: '省人民',
      province: '浙江省',
      city: '杭州市',
      district: '拱墅区',
      address: '拱墅区上塘路158号（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['器官移植', '微创外科'],
      sortWeight: 95,
    }),
    seedRow({
      name: '浙江省肿瘤医院',
      shortName: '省肿瘤',
      province: '浙江省',
      city: '杭州市',
      district: '拱墅区',
      address: '拱墅区半山东路1号（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['肿瘤内科', '放疗'],
      sortWeight: 94,
    }),
    seedRow({
      name: '杭州市第一人民医院',
      shortName: '市一医院',
      province: '浙江省',
      city: '杭州市',
      district: '上城区',
      address: '上城区浣纱路261号（多院区请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['急诊', '消化内科'],
      sortWeight: 92,
    }),
    seedRow({
      name: '杭州市中医院',
      shortName: '市中院',
      province: '浙江省',
      city: '杭州市',
      district: '西湖区',
      address: '西湖区体育场路453号等（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['中医内科', '针灸推拿'],
      sortWeight: 90,
    }),
    seedRow({
      name: '杭州市西溪医院',
      shortName: '西溪医院',
      province: '浙江省',
      city: '杭州市',
      district: '西湖区',
      address: '西湖区留下街道横埠街2号（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三级',
      ownershipType: '政府办',
      keyDepartments: ['感染科', '肝病'],
      sortWeight: 82,
    }),
    seedRow({
      name: '杭州市红十字会医院',
      shortName: '红会医院',
      province: '浙江省',
      city: '杭州市',
      district: '拱墅区',
      address: '拱墅区环城东路208号（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['中西医结合', '骨伤科'],
      sortWeight: 88,
    }),
    seedRow({
      name: '萧山区第一人民医院',
      shortName: '萧山人民',
      province: '浙江省',
      city: '杭州市',
      district: '萧山区',
      address: '萧山区城厢街道市心南路199号附近（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三乙',
      ownershipType: '政府办',
      keyDepartments: ['区域综合'],
      sortWeight: 58,
    }),
    seedRow({
      name: '余杭区第一人民医院',
      shortName: '余杭人民',
      province: '浙江省',
      city: '杭州市',
      district: '余杭区',
      address: '余杭区临平街道迎宾路369号附近（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三乙',
      ownershipType: '政府办',
      keyDepartments: ['区域综合'],
      sortWeight: 57,
    }),
    seedRow({
      name: '富阳区第一人民医院',
      shortName: '富阳人民',
      province: '浙江省',
      city: '杭州市',
      district: '富阳区',
      address: '富阳区富春街道北环路429号附近（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '二甲',
      ownershipType: '政府办',
      keyDepartments: ['县域综合救治'],
      sortWeight: 52,
    }),
    seedRow({
      name: '临安区人民医院',
      shortName: '临安人民',
      province: '浙江省',
      city: '杭州市',
      district: '临安区',
      address: '临安区锦城街道衣锦街附近（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '二甲',
      ownershipType: '政府办',
      keyDepartments: ['县域综合救治'],
      sortWeight: 50,
    }),
    seedRow({
      name: '桐庐县第一人民医院',
      shortName: '桐庐人民',
      province: '浙江省',
      city: '杭州市',
      district: '桐庐县',
      address: '桐庐县桐君街道学圣路附近（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '二甲',
      ownershipType: '政府办',
      keyDepartments: ['县域综合救治'],
      sortWeight: 48,
    }),
    seedRow({
      name: '建德市第一人民医院',
      shortName: '建德人民',
      province: '浙江省',
      city: '杭州市',
      district: '建德市',
      address: '建德市新安江街道严州大道附近（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '二甲',
      ownershipType: '政府办',
      keyDepartments: ['县域综合救治'],
      sortWeight: 48,
    }),
    seedRow({
      name: '淳安县第一人民医院',
      shortName: '淳安人民',
      province: '浙江省',
      city: '杭州市',
      district: '淳安县',
      address: '淳安县千岛湖镇新安西路附近（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '二甲',
      ownershipType: '政府办',
      keyDepartments: ['县域综合救治'],
      sortWeight: 46,
    }),
    /* ─── 上海市 ─── */
    seedRow({
      name: '复旦大学附属华山医院',
      shortName: '华山医院',
      province: '上海市',
      city: '上海市',
      district: '静安区',
      address: '静安区乌鲁木齐中路12号（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['神经内科', '皮肤科', '感染科'],
      sortWeight: 100,
    }),
    seedRow({
      name: '复旦大学附属中山医院',
      shortName: '中山医院',
      province: '上海市',
      city: '上海市',
      district: '徐汇区',
      address: '徐汇区枫林路180号（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['心内科', '普外科', '肝肿瘤'],
      sortWeight: 100,
    }),
    seedRow({
      name: '上海交通大学医学院附属瑞金医院',
      shortName: '瑞金医院',
      province: '上海市',
      city: '上海市',
      district: '黄浦区',
      address: '黄浦区瑞金二路197号（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['血液科', '内分泌', '烧伤'],
      sortWeight: 100,
    }),
    seedRow({
      name: '上海交通大学医学院附属仁济医院（东院）',
      shortName: '仁济东院',
      province: '上海市',
      city: '上海市',
      district: '浦东新区',
      address: '浦东新区浦建路160号（多院区请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['消化科', '泌尿科', '妇产科'],
      sortWeight: 98,
    }),
    seedRow({
      name: '上海交通大学医学院附属新华医院',
      shortName: '新华医院',
      province: '上海市',
      city: '上海市',
      district: '杨浦区',
      address: '杨浦区控江路1665号（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['儿科', '小儿外科'],
      sortWeight: 97,
    }),
    seedRow({
      name: '复旦大学附属肿瘤医院',
      shortName: '肿瘤医院',
      province: '上海市',
      city: '上海市',
      district: '徐汇区',
      address: '徐汇区东安路270号（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['肿瘤外科', '放疗'],
      sortWeight: 96,
    }),
    seedRow({
      name: '上海市第一人民医院',
      shortName: '市一上海',
      province: '上海市',
      city: '上海市',
      district: '虹口区',
      address: '虹口区武进路85号等（多院区请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['眼科', '综合诊疗'],
      sortWeight: 95,
    }),
    seedRow({
      name: '上海市第六人民医院',
      shortName: '市六医院',
      province: '上海市',
      city: '上海市',
      district: '徐汇区',
      address: '徐汇区宜山路600号（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['骨科', '内分泌代谢'],
      sortWeight: 95,
    }),
    seedRow({
      name: '海军军医大学第二附属医院（上海长征医院）',
      shortName: '长征医院',
      province: '上海市',
      city: '上海市',
      district: '黄浦区',
      address: '黄浦区成都北路500号（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['脊柱外科', '肾内科'],
      sortWeight: 93,
    }),
    seedRow({
      name: '海军军医大学第一附属医院（长海医院）',
      shortName: '长海医院',
      province: '上海市',
      city: '上海市',
      district: '杨浦区',
      address: '杨浦区长海路168号（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['肝胆胰', '烧创伤'],
      sortWeight: 93,
    }),
    seedRow({
      name: '同济大学附属同济医院',
      shortName: '同济医院',
      province: '上海市',
      city: '上海市',
      district: '普陀区',
      address: '普陀区新村路389号（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['急诊', '心血管'],
      sortWeight: 91,
    }),
    seedRow({
      name: '上海交通大学医学院附属第九人民医院',
      shortName: '九院',
      province: '上海市',
      city: '上海市',
      district: '黄浦区',
      address: '黄浦区制造局路639号（多院区请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['口腔', '整复外科'],
      sortWeight: 94,
    }),
    seedRow({
      name: '中国福利会国际和平妇幼保健院',
      shortName: '国妇婴',
      province: '上海市',
      city: '上海市',
      district: '徐汇区',
      address: '徐汇区衡山路910号等（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['妇产科', '妇幼保健'],
      sortWeight: 92,
    }),
    seedRow({
      name: '上海交通大学医学院附属上海儿童医学中心',
      shortName: '儿中心',
      province: '上海市',
      city: '上海市',
      district: '浦东新区',
      address: '浦东新区东方路1678号（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['儿童心脏', '儿童血液'],
      sortWeight: 92,
    }),
    seedRow({
      name: '上海市东方医院（同济大学附属东方医院）',
      shortName: '东方医院',
      province: '上海市',
      city: '上海市',
      district: '浦东新区',
      address: '浦东新区即墨路150号（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['急诊', '胸痛中心'],
      sortWeight: 90,
    }),
    seedRow({
      name: '上海市肺科医院',
      shortName: '肺科医院',
      province: '上海市',
      city: '上海市',
      district: '杨浦区',
      address: '杨浦区政民路507号（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['呼吸科', '胸外科'],
      sortWeight: 90,
    }),
    seedRow({
      name: '上海中医药大学附属龙华医院',
      shortName: '龙华医院',
      province: '上海市',
      city: '上海市',
      district: '徐汇区',
      address: '徐汇区宛平南路725号（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['中医肿瘤', '针灸'],
      sortWeight: 89,
    }),
    seedRow({
      name: '上海中医药大学附属曙光医院（东院）',
      shortName: '曙光东院',
      province: '上海市',
      city: '上海市',
      district: '浦东新区',
      address: '浦东新区张衡路528号（请以官网为准）',
      phoneMain: null,
      hospitalLevel: '三甲',
      ownershipType: '政府办',
      keyDepartments: ['中医内科', '骨伤科'],
      sortWeight: 89,
    }),
  ];
}
